# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [1]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /var/data/python/lib/python3.13/site-packages (3.0.5)
Requirement already satisfied: numpy in /var/data/python/lib/python3.13/site-packages (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /var/data/python/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /var/data/python/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [131]:
# Load the Food choices data set.

food_data_set_path = 'data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [93]:
# Count by hand. (lol kidding)
len(df_food)

125

In [94]:
# Try to print or display it nicely.
df_food

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,cook,comfort_food_reasons_coded.1,cuisine,diet_current,diet_current_coded,drink,eating_changes,eating_changes_coded,eating_changes_coded1,eating_out,employment,ethnic_food,exercise,father_education,father_profession,fav_cuisine,fav_cuisine_coded,fav_food,food_childhood,fries,fruit_day,grade_level,greek_food,healthy_feeling,healthy_meal,ideal_diet,ideal_diet_coded,income,indian_food,italian_food,life_rewarding,marital_status,meals_dinner_friend,mother_education,mother_profession,nutritional_check,on_off_campus,parents_cook,pay_meal_out,persian_food,self_perception_weight,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,2.0,9,NaN,eat good and exercise,1,1.0,eat faster,1,1,3,3.0,1,1.0,5.0,profesor,Arabic cuisine,3,1.0,rice and chicken,2,5,2,5,2,looks not oily,being healthy,8,5.0,5,5,1.0,1.0,"rice, chicken, soup",1.0,unemployed,5,1.0,1,2,5.0,3.0,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,3.0,1,1.0,I eat about three times a day with some snacks...,2,2.0,I eat out more than usual.,1,2,2,2.0,4,1.0,2.0,Self employed,Italian,1,1.0,"chicken and biscuits, beef soup, baked beans",1,4,4,4,5,"Grains, Veggies, (more of grains and veggies),...",Try to eat 5-6 small meals a day. While trying...,3,4.0,4,4,1.0,2.0,"Pasta, steak, chicken",4.0,Nurse RN,4,1.0,1,4,4.0,3.0,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,1.0,1,3.0,"toast and fruit for breakfast, salad for lunch...",3,1.0,sometimes choosing to eat fast food instead of...,1,3,2,3.0,5,2.0,2.0,owns business,italian,1,3.0,"mac and cheese, pizza, tacos",1,5,3,5,6,usually includes natural ingredients; nonproce...,i would say my ideal diet is my current diet,6,6.0,5,5,7.0,2.0,"chicken and rice with veggies, pasta, some kin...",2.0,owns business,4,2.0,1,3,5.0,6.0,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,2.0,2,2.0,"College diet, cheap and easy foods most nights...",2,2.0,Accepting cheap and premade/store bought foods,1,3,2,3.0,5,3.0,2.0,Mechanic,Turkish,3,1.0,"Beef stroganoff, tacos, pizza",2,4,4,5,7,"Fresh fruits& vegetables, organic meats","Healthy, fresh veggies/fruits & organic foods",2,6.0,5,5,2.0,2.0,Grilled chicken \rStuffed Shells\rHomemade Chili,4.0,Special Education Teacher,2,1.0,1,2,5.0,5.0,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,1.0,1,2.0,I try to eat healthy but often struggle becaus...,2,2.0,I have eaten generally the same foods but I do...,3,4,2,2.0,4,1.0,4.0,IT,Italian,1,3.0,"Pasta, chicken tender, pizza",1,4,4,4,6,"A lean protein such as grilled chicken, green ...",Ideally I would like to be able to eat healthi...,2,6.0,2,5,1.0,1.0,"Chicken Parmesan, Pulled Pork, Spaghetti and m...",5.0,Substance Abuse Conselor,3,1.0,1,4,2.0,4.0,1.0,1.0,4,940.0,500,Softball,4,2,760,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.5,1,1,610,4.0,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,NaN,3.0,2,1.0,"My diet consists mainly of coffee, water, frui...",2,2.0,I have noticed there is less time for a prepar...,1,3,2,1.0,4,2.0,4.0,Accountant,Italian,1,1.0,Stromboli Mac and Cheese and Pizza,1,5,4,5,5,mainly protein and vegetables with a complex c...,My ideal diet would consist of a majority of w...,6,4.0,3,5,7.0,1.0,"pasta, fish, steak",3.0,Radiological Technician,5,3.0,1,4,3.0,4.0,1.0,1.0,5,940.0,500,Softball,5,1,1315,156
121,3,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,3.0,3,NaN,A college student with an imbalanced diet tryi...,2,1.0,Eating Pizza as an excuse when there is nothin...,1,3,4,3.0,3,2.0,5.0,Doctor,Mexican Food,2,1.0,"Isombe , Plantains and Ugali",1,4,4,1,5,"A healthy meal is a variety of food , organic ...",Eating home cooked meals everyday and being ab...,5,2.0,5,5,7.0,1.0,Fried Rice \rBaked potatoes \rCurry Chicken,2.0,Public Health Advisor,3,1.0,3,4,1.0,4.0,1.0,NaN,4,940.0,500,basketball,5,2,1315,180
122,3.882,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",sadness,NaN,3.0,3,NaN,"Rice, oatmeal, and tea",2,1.0,less rice,1,3,3,3.0,5,2.0,5.0,CEO of company,Korean,4,1.0,Rice and potato,1,4,3,5,6,lots of vegetables,lots of veggies,2,2.0,5,3,10.0,1.0,"meat, rice, kimchi",1.0,Real Estate manageer,3,1.0,2,4,5.0,4.0,1.0,2.0,5,580.0,690,none,4,2,1315,120
123,3,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,3.0,7,1.0,I try to eat as healthy as possible everyday. ...,1,2.0,I don't eat as much on a daily basis since com...,1,8,5,2.0,2,1.0,3.0,Store manager at Giant Eagle,Italian,1,3.0,pizza and spaghetti,1,5,1,1,1,"A protein, a fruit, a starch, and a salad or s...",My ideal diet is the diet i am currently on. ...,6,4.0,1,5,1.0,1.0,"Pizza, Spaghetti, Baked Ziti",2.0,Receptionist for a medical supply company,4,1.0,2,3,1.0,2.0,2.0,2.0,1,940.0,500,NaN,3,1,1315,135
124,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,NaN,5,3.0,high in protein and low in carbohydrates.,1,1.0,I have learned to eat more vegetables.,2,5,1,2.0,3,2.0,4.0,Journalist,HISPANIC CUISINE.,2,1.0,"rice, beans, and chicken / pizza/ tenders",1,3,3,2,3,"a cup of rice, vegetables, and meat.","Being able to balance between sweets, vegetabl...",3,5.0,2,3,5.0,2.0,"Vegetables, Meat, and rice.",3.0,House-wife,5,1.0,3,3,2.0,3.0,1.0,2.0,2,725.0,345,NaN,4,2,575,135

What are the columns and their types in this data set?

In [95]:
# Show the column names and their types.
df_food.head(0).dtypes

GPA                                 str
Gender                            int64
breakfast                         int64
calories_chicken                  int64
calories_day                    float64
calories_scone                  float64
coffee                            int64
comfort_food                        str
comfort_food_reasons                str
comfort_food_reasons_coded      float64
cook                            float64
comfort_food_reasons_coded.1      int64
cuisine                         float64
diet_current                        str
diet_current_coded                int64
drink                           float64
eating_changes                      str
eating_changes_coded              int64
eating_changes_coded1             int64
eating_out                        int64
employment                      float64
ethnic_food                       int64
exercise                        float64
father_education                float64
father_profession                   str
fav_cuisine                         str
fav_cuisine_coded                 int64
fav_food                        float64
food_childhood                      str
fries                             int64
fruit_day                         int64
grade_level                       int64
greek_food                        int64
healthy_feeling                   int64
healthy_meal                        str
ideal_diet                          str
ideal_diet_coded                  int64
income                          float64
indian_food                       int64
italian_food                      int64
life_rewarding                  float64
marital_status                  float64
meals_dinner_friend                 str
mother_education                float64
mother_profession                   str
nutritional_check                 int64
on_off_campus                   float64
parents_cook                      int64
pay_meal_out                      int64
persian_food                    float64
self_perception_weight          float64
soup                            float64
sports                          float64
thai_food                         int64
tortilla_calories               float64
turkey_calories                   int64
type_sports                         str
veggies_day                       int64
vitamins                          int64
waffle_calories                   int64
weight                              str
dtype: object

In [96]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.
pd.set_option("display.max_columns",100)

df_info = df_food.dtypes.to_frame(name="Data Type").reset_index()
df_info.columns = ["Column Name", "Data Type"]

# Display the final summary table
df_info

                     Column Name Data Type
0                            GPA       str
1                         Gender     int64
2                      breakfast     int64
3               calories_chicken     int64
4                   calories_day   float64
5                 calories_scone   float64
6                         coffee     int64
7                   comfort_food       str
8           comfort_food_reasons       str
9     comfort_food_reasons_coded   float64
10                          cook   float64
11  comfort_food_reasons_coded.1     int64
12                       cuisine   float64
13                  diet_current       str
14            diet_current_coded     int64
15                         drink   float64
16                eating_changes       str
17          eating_changes_coded     int64
18         eating_changes_coded1     int64
19                    eating_out     int64
20                    employment   float64
21                   ethnic_food     int64
22                      exercise   float64
23              father_education   float64
24             father_profession       str
25                   fav_cuisine       str
26             fav_cuisine_coded     int64
27                      fav_food   float64
28                food_childhood       str
29                         fries     int64
30                     fruit_day     int64
31                   grade_level     int64
32                    greek_food     int64
33               healthy_feeling     int64
34                  healthy_meal       str
35                    ideal_diet       str
36              ideal_diet_coded     int64
37                        income   float64
38                   indian_food     int64
39                  italian_food     int64
40                life_rewarding   float64
41                marital_status   float64
42           meals_dinner_friend       str
43              mother_education   float64
44             mother_profession       str
45             nutritional_check     int64
46                 on_off_campus   float64
47                  parents_cook     int64
48                  pay_meal_out     int64
49                  persian_food   float64
50        self_perception_weight   float64
51                          soup   float64
52                        sports   float64
53                     thai_food     int64
54             tortilla_calories   float64
55               turkey_calories     int64
56                   type_sports       str
57                   veggies_day     int64
58                      vitamins     int64
59               waffle_calories     int64
60                        weight       str

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [97]:
# Remove ‘em.
df_food_col_subset=df_food[['calories_day','weight','Gender']]
df_food_col_subset

     calories_day                    weight  Gender
0             NaN                       187       2
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
..            ...                       ...     ...
120           4.0                       156       1
121           2.0                       180       1
122           NaN                       120       1
123           4.0                       135       2
124           NaN                       135       1

[125 rows x 3 columns]

In [98]:
# Is there a second way to remove columns?

gender_col = df_food.pop('Gender')
calories_col = df_food.pop('calories_day')
weight_col = df_food.pop('weight')
df_food_col_subset2=pd.concat([calories_col, weight_col, gender_col], axis=1)
df_food_col_subset2.head()

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

In [101]:
# 🚀 Extra credit: What about a third way to remove columns?
# Drops the column at index position 3 from the DataFrame copy
mask=[col  in ['Gender','calories_day','weight'] for col in df_food.columns]
df_food_col_subset = df_food.loc[:, mask]
df_food_col_subset.head()

   Gender  calories_day                    weight
0       2           NaN                       187
1       1           3.0                       155
2       1           4.0  I'm not answering this.
3       1           3.0             Not sure, 240
4       1           2.0                       190

What about `NaN`s? How many are there?

In [102]:
# Count ‘em.
countNaN=df_food.isnull().sum()
print(f"Number of missing values in each column: {countNaN}")

Number of missing values in each column: GPA                              2
Gender                           0
breakfast                        0
calories_chicken                 0
calories_day                    19
calories_scone                   1
coffee                           0
comfort_food                     1
comfort_food_reasons             2
comfort_food_reasons_coded      19
cook                             3
comfort_food_reasons_coded.1     0
cuisine                         17
diet_current                     1
diet_current_coded               0
drink                            2
eating_changes                   3
eating_changes_coded             0
eating_changes_coded1            0
eating_out                       0
employment                       9
ethnic_food                      0
exercise                        13
father_education                 1
father_profession                3
fav_cuisine                      2
fav_cuisine_coded                0
fav_food                         2
food_childhood                   1
fries                            0
fruit_day                        0
grade_level                      0
greek_food                       0
healthy_feeling                  0
healthy_meal                     1
ideal_diet                       1
ideal_diet_coded                 0
income                           1
indian_food                      0
italian_food                     0
life_rewarding                   1
marital_status                   1
meals_dinner_friend              3
mother_education                 3
mother_profession                2
nutritional_check                0
on_off_campus                    1
parents_cook                     0
pay_meal_out                     0
persian_food                     1
self_perception_weight           1
soup                             1
sports                           2
thai_food                        0
tortilla_calories                1
turkey_calories                  0
type_sports                     26
veggies_day                      0
vitamins                         0
waffle_calories                  0
weight                           2
dtype: int64

In [103]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.
df_nan_summary = df_food.isnull().sum().to_frame(name='NaN Count').reset_index()
df_nan_summary.columns = ['Column Name', 'NaN Count']

# Displays your beautifully formatted missing values table
df_nan_summary

                     Column Name  NaN Count
0                            GPA          2
1                         Gender          0
2                      breakfast          0
3               calories_chicken          0
4                   calories_day         19
5                 calories_scone          1
6                         coffee          0
7                   comfort_food          1
8           comfort_food_reasons          2
9     comfort_food_reasons_coded         19
10                          cook          3
11  comfort_food_reasons_coded.1          0
12                       cuisine         17
13                  diet_current          1
14            diet_current_coded          0
15                         drink          2
16                eating_changes          3
17          eating_changes_coded          0
18         eating_changes_coded1          0
19                    eating_out          0
20                    employment          9
21                   ethnic_food          0
22                      exercise         13
23              father_education          1
24             father_profession          3
25                   fav_cuisine          2
26             fav_cuisine_coded          0
27                      fav_food          2
28                food_childhood          1
29                         fries          0
30                     fruit_day          0
31                   grade_level          0
32                    greek_food          0
33               healthy_feeling          0
34                  healthy_meal          1
35                    ideal_diet          1
36              ideal_diet_coded          0
37                        income          1
38                   indian_food          0
39                  italian_food          0
40                life_rewarding          1
41                marital_status          1
42           meals_dinner_friend          3
43              mother_education          3
44             mother_profession          2
45             nutritional_check          0
46                 on_off_campus          1
47                  parents_cook          0
48                  pay_meal_out          0
49                  persian_food          1
50        self_perception_weight          1
51                          soup          1
52                        sports          2
53                     thai_food          0
54             tortilla_calories          1
55               turkey_calories          0
56                   type_sports         26
57                   veggies_day          0
58                      vitamins          0
59               waffle_calories          0
60                        weight          2

In [104]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.
nan_summary = df_food.isnull().sum() \
    .to_frame(name='Nan count') \
    .reset_index() \
    .rename(columns={'index':'Column Name'})
nan_summary

                     Column Name  Nan count
0                            GPA          2
1                         Gender          0
2                      breakfast          0
3               calories_chicken          0
4                   calories_day         19
5                 calories_scone          1
6                         coffee          0
7                   comfort_food          1
8           comfort_food_reasons          2
9     comfort_food_reasons_coded         19
10                          cook          3
11  comfort_food_reasons_coded.1          0
12                       cuisine         17
13                  diet_current          1
14            diet_current_coded          0
15                         drink          2
16                eating_changes          3
17          eating_changes_coded          0
18         eating_changes_coded1          0
19                    eating_out          0
20                    employment          9
21                   ethnic_food          0
22                      exercise         13
23              father_education          1
24             father_profession          3
25                   fav_cuisine          2
26             fav_cuisine_coded          0
27                      fav_food          2
28                food_childhood          1
29                         fries          0
30                     fruit_day          0
31                   grade_level          0
32                    greek_food          0
33               healthy_feeling          0
34                  healthy_meal          1
35                    ideal_diet          1
36              ideal_diet_coded          0
37                        income          1
38                   indian_food          0
39                  italian_food          0
40                life_rewarding          1
41                marital_status          1
42           meals_dinner_friend          3
43              mother_education          3
44             mother_profession          2
45             nutritional_check          0
46                 on_off_campus          1
47                  parents_cook          0
48                  pay_meal_out          0
49                  persian_food          1
50        self_perception_weight          1
51                          soup          1
52                        sports          2
53                     thai_food          0
54             tortilla_calories          1
55               turkey_calories          0
56                   type_sports         26
57                   veggies_day          0
58                      vitamins          0
59               waffle_calories          0
60                        weight          2

We gotta remove those `NaN`s―the entire row.

In [113]:
# Drop ‘em in-place.

dropNaN = df_food.dropna(inplace=True)

In [114]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂

df_food

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,cook,comfort_food_reasons_coded.1,cuisine,diet_current,diet_current_coded,drink,eating_changes,eating_changes_coded,eating_changes_coded1,eating_out,employment,ethnic_food,exercise,father_education,father_profession,fav_cuisine,fav_cuisine_coded,fav_food,food_childhood,fries,fruit_day,grade_level,greek_food,healthy_feeling,healthy_meal,ideal_diet,ideal_diet_coded,income,indian_food,italian_food,life_rewarding,marital_status,meals_dinner_friend,mother_education,mother_profession,nutritional_check,on_off_campus,parents_cook,pay_meal_out,persian_food,self_perception_weight,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,3.0,1,1.0,I eat about three times a day with some snacks...,2,2.0,I eat out more than usual.,1,2,2,2.0,4,1.0,2.0,Self employed,Italian,1,1.0,"chicken and biscuits, beef soup, baked beans",1,4,4,4,5,"Grains, Veggies, (more of grains and veggies),...",Try to eat 5-6 small meals a day. While trying...,3,4.0,4,4,1.0,2.0,"Pasta, steak, chicken",4.0,Nurse RN,4,1.0,1,4,4.0,3.0,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,1.0,1,3.0,"toast and fruit for breakfast, salad for lunch...",3,1.0,sometimes choosing to eat fast food instead of...,1,3,2,3.0,5,2.0,2.0,owns business,italian,1,3.0,"mac and cheese, pizza, tacos",1,5,3,5,6,usually includes natural ingredients; nonproce...,i would say my ideal diet is my current diet,6,6.0,5,5,7.0,2.0,"chicken and rice with veggies, pasta, some kin...",2.0,owns business,4,2.0,1,3,5.0,6.0,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,1.0,1,2.0,I try to eat healthy but often struggle becaus...,2,2.0,I have eaten generally the same foods but I do...,3,4,2,2.0,4,1.0,4.0,IT,Italian,1,3.0,"Pasta, chicken tender, pizza",1,4,4,4,6,"A lean protein such as grilled chicken, green ...",Ideally I would like to be able to eat healthi...,2,6.0,2,5,1.0,1.0,"Chicken Parmesan, Pulled Pork, Spaghetti and m...",5.0,Substance Abuse Conselor,3,1.0,1,4,2.0,4.0,1.0,1.0,4,940.0,500,Softball,4,2,760,190
6,3.8,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,2.0,1,1.0,I eat a lot of chicken and broccoli for dinner...,3,1.0,I started eating a lot less and healthier beca...,2,5,2,3.0,5,1.0,4.0,Assembler,Thai,4,1.0,"grilled chicken, hamburgers",1,4,4,5,4,"Protein, vegetables, fruit, and some carbs",I would ideally like to eat more fresh fruits ...,2,4.0,5,5,8.0,1.0,"Grilled chicken, steak, pizza",4.0,Journalist,4,2.0,2,2,5.0,4.0,1.0,1.0,5,940.0,690,soccer,4,1,1315,180
7,3.3,1,1,720,3.0,420.0,1,"Ice cream, cheeseburgers, chips.",I eat comfort food when im stressed out from s...,1.0,3.0,1,1.0,"I eat a very healthy diet. Ocassionally, i wil...",1,2.0,"Freshmen year i ate very unhealthy, but now it...",2,5,2,2.0,2,2.0,3.0,Business guy,Anything american style.,5,1.0,"chicken, cheesey potatoes, and hot dogs",1,5,2,3,3,A healthy meal has a piece of meat followed by...,My ideal diet is filled with a lot of fruit an...,2,5.0,1,3,3.0,1.0,"chicken, steak, pasta",2.0,cook,4,1.0,1,5,1.0,3.0,1.0,2.0,1,725.0,500,none,4,2,1315,137
9,3.3,1,1,430,3.0,315.0,2,"Mac and cheese, chocolate, and pasta","Stress, anger and sadness",1.0,3.0,1,1.0,I eat healthy all the time when possible. I tr...,1,1.0,I cook a lot of my own foods back at home so n...,1,3,3,3.0,5,1.0,5.0,commissioner of erie county,Italian,1,1.0,"Pasta, Eggs, Pancakes",1,5,1,5,3,Chicken and rice with a side of veggies.,"Lots of protein, carbs, and fruits and veggies.",2,4.0,4,5,3.0,2.0,pasta salad and bread,5.0,Pharmaceutical rep,5,1.0,3,3,4.0,3.0,1.0,1.0,4,580.0,345,field hockey,5,1,900,125
10,3.5,1,1,610,3.0,980.0,2,"Pasta, grandma homemade chocolate cake anythin...",Boredom,2.0,1.0,2,1.0,i eat very healthy. Maybe eat out 1-2 times a ...,1,2.0,Nun,3,4,2,1.0,5,1.0,2.0,Idk,Orange chicken and chow mani noodles,4,1.0,Chicken,1,5,3,1,9,"Chicken, and veggies","Chicken, fish",7,3.0,1,5,8.0,1.0,"chicken al king, spaghetti, fish",4.0,Chidos Cleaners,2,3.0,1,2,2.0,1.0,1.0,1.0,2,940.0,345,soccer,5,2,900,116
11,3.904,1,1,720,4.0,420.0,2,"chocolate, pasta, soup, chips, popcorn","sadness, stress, cold weather",3.0,3.0,3,1.0,"I am very health concious. I eat many fruits, ...",1,1.0,Less meat.,4,5,1,2.0,5,1.0,3.0,Home Marker,Italian,1,1.0,Scalloped potatoes and ham,1,5,2,5,1,"lean protein, veggies, fruit, complex carbs",More healthy varienty.,2,5.0,5,5,1.0,2.0,"Chicken parm, Fish, Pasta dishes",4.0,Court Reporter,5,1.0,1,3,5.0,2.0,1.0,1.0,5,940.0,500,Running,5,1,900,110
12,3.4,2,1,430,3.0,420.0,2,"Cookies, popcorn, and chips","Sadness, boredom, late night snack",3.0,5.0,3,1.0,I focus mostly on proteins and fruits. I eat a...,1,2.0,I have been eating a lot more salads and soups.,2,5,1,3.0,4,3.0,3.0,Shirt designer,Chinese,4,3.0,"Pizza, chicken wings, and corn on the cob",1,4,1,3,9,A salad with a reasonable amount of dressing a...,My ideal diet would be the proper portions of ...,1,5.0,3,4,9.0,2.0,"Cereal, pizza, toast",4.0,Child care provider,2,1.0,2,2,3.0,5.0,2.0,1.0,3,940.0,500,Soccer and basketball,3,2,575,264
13,3.6,1,1,610,3.0,420.0,2,"ice cream, cake, chocolate","stress, boredom, special occasions",1.0,2.0,1,1.0,Not as healthy when I am at school compared to...,2,2.0,not as healthy because healthy food goes bad q...,1,3,4,2.0,5,2.0,2.0,business owner,italian,1,1.0,"steak, lasagna, crab",1,5,3,4,8,Lots of vegetabls with some grains like rice. ...,organic/healthy. fruits and vegetables but sti...,2,5.0,3,5,10.0,2.0,"pasta, chicken, steak",4.0,business owner,2,2.0,2,3,3.0,3.0,1.0,1.0,5,1165.0,850,intramural volleyball,5,2,1315,123
14,3.1,2,1,610,3.0,420.0,2,"Pizza, fruit, spaghetti, chicken and Potatoes","Friends, environment and boredom",2.0,3.0,2,1.0,"Making sure I have enough protein intake, as w...",1,2.0,"I knew I would eat alot my freshmen year, befo...",3,4,2,3.0,4,2.0,4.0,Commidity trader,Chinese,4,3.0,Pizza,1,5,3,4,2,Green and not greasy,"Eat a little less than I usually do, and intak...",1,5.0,2,3,1.0,1.0,"Pizza, chicken and rice, roast beef.",4.0,Charity worker,2,2.0,2,3,1.0,3.0,1.0,1.0,4,940.0,500,Hockey,5,1,900,185
17,3.6,2,1,430,3.0,980.0,2,"chips, cookies, ice cream",I usually only eat comfort food when I'm bored...,2.0,3.0,2,1.0,My current diet is eggs and a meat every morni...,3,2.0,"I would say i just eat a little more, but not ...",1,2,2,3.0,4,1.0,2.0,self employed construction,American or Italian,5,3.0,"chicken fingers, steak, mac and cheese",1,3,1,3,8,for me usually a big piece of chicken or steak...,"I like how my diet it now. However, after my s...",1,6.0,3,5,7.0,2.0,Grilled chicken or steak with veggies and rice...,2.0,stay at home mom,4,1.0,1,6,2.0,2.0,1.0,1.0,3,940.0,500,hockey,4,2,900,170
18,3.4,1,1,720,3.0,980.0,1,"Chocolate, ice crea","Sadness, stress",3.0,3.0,3,1.0,I eat lots of fruit and veggies. I eat lots of...,1,1.0,I ate at the food hall.,4,6,3,2.0,1,3.0,5.0,Engineer,Chicken,5,3.0,Chicken,1,5,2,3,6,Everything from food group,Lots of fruit and veggies. Lots of chicken.,2,5.0,1,5,9.0,2.0,"Spaghetti, Chicken, Steak",3.0,Daycare provider,2,1.0,1,2,1.0,3.0,2.0,2.0,1,1165.0,690,dancing,5,1,1315,135
20,3.3,2,1,610,3.0,980.0,2,"Fast food, pizza, subs","happiness, satisfaction",7.0,5.0,7,1.0,"I eat 2 meals a day, lunch and dinner",2,2.0,Late night food,1,3,4,2.0,4,1.0,5.0,CFO,Mexican,2,3.0,"pizza, chicken fingers",1,2,2,2,5,"Rice, Meat, vegetable",3 smaller meals a day,1,6.0,1,4,2.0,1.0,"Chicken, Pasta, Veal",4.0,Teacher,2,1.0,1,2,1.0,6.0,1.0,1.0,1,1165.0,850,Soccer,3,2,1315,175
22,3.7,2,1,610,3.0,420.0,1,"burgers, chips, cookies","sadness, depression",3.0,5.0,3,2.0,balanced,1,1.0,got worse,1,3,1,2.0,3,1.0,4.0,accountant,italian,1,1.0,pasta,2,4,1,4,2,"pasta. veg, water","fruit, veg and protien",2,6.0,5,5,5.0,1.0,"pasta, pizza",4.0,Underwiriter,3,1.0,3,5,2.0,2.0,1.0,1.0,4,940.0,850,tennis soccer gym,3,1,1315,185
23,3.7,2,2,610,3.0,420.0,2,"Chilli, soup, pot pie",Stress and boredom,1.0,4.0,1,1.0,2 meals a day. Rarely eat snacks. Fairly balan...,1,1.0,Drink coffee all the time.,1,7,2,2.0,5,3.0,4.0,Commercial Real Estate,Asian,4,1.0,Chicken Nuggets,1,3,3,2,4,"Protein, vegetables, grains",3 healthy meals a day. No caffiene.,1,4.0,4,5,5.0,1.0,"Pizza, Pasta, Poutine",2.0,Beautician,2,1.0,2,3,2.0,3.0,1.0,1.0,4,940.0,690,Gaelic Football,4,1,1315,185
25,2.8,1,2,720,3.0,420.0,2,"chocolate, ice cream/milkshake, cookies",boredom,2.0,3.0,2,1.0,"vegetarian, eat breakfast some days before cla...",1,1.0,"none, I have dormed since high school",3,4,2,3.0,2,1.0,4.0,VP of,don't have one,0,3.0,"Chicken parm, beef stroganof, tacos",1,4,1,3,8,"good portions, lots of color, targets main foo...","healthy, colorful, tasty, room for desserts",2,6.0,3,3,5.0,1.0,Pasta\rTake out,3.0,Medical biller,4,1.0,1,3,3.0,3.0,1.0,1.0,3,1165.0,690,Ice hockey,3,2,760,125
26,3.7,2,1,610,2.0,420.0,1,"Chips, ice cream, microwaveable foods","Boredom, lazyniss",2.0,3.0,2,1.0,"Most healthy diet, but since I'm an athlete ha...",1,1.0,Tend to eat more fried foods,1,3,2,2.0,2,1.0,4.0,Beverage and Food Sales,Italian food,1,1.0,"Chicken Parm, Pizza",1,3,2,1,9,"A rice, a vegetable, a piece of meat","Very healthy diet, and to cook at home with or...",5,5.0,1,5,9.0,2.0,Chicken parm,2.0,Doctors Billing Assiant,2,1.0,1,4,1.0,2.0,2.0,1.0,2,1165.0,850,Hockey,3,2,1315,160
27,3,2,1,610,4.0,980.0,2,"Chicken fingers, pizza",Boredom,2.0,4.0,2,1.0,Very healthy. Good balance of proteins and veg...,1,2.0,A lot healthier,2,5,2,3.0,3,1.0,5.0,Dentist,Mexican,2,1.0,Steak,1,5,1,3,9,"Salad, vegetable, carb, protein",My current diet,6,6.0,3,4,9.0,2.0,"Steak, lobster, chicken",5.0,Dentist,4,1.0,1,6,2.0,2.0,1.0,1.0,3,1165.0,500,Lacrosse,5,1,1315,175
31,4,2,1,610,3.0,420.0,2,"chips and dip, pepsi,","stres, boredom, and nighttime",1.0,2.0,1,1.0,Diet consists of 3000-4000 calories a day well...,2,2.0,none,3,4,2,3.0,5,2.0,4.0,deceased,italian,1,1.0,chicken and biscuits,1,5,2,5,5,"4-6 ounces chicken or fish, side of potatoes, ...","diet of 1500-2000 calories of white meat, vege...",1,4.0,4,5,3.0,1.0,"Chicken, Steak, Pasta",2.0,management,4,4.0,1,3,3.0,4.0,2.0,2.0,4,940.0,690,none organized,5,1,1315,205
34,3.65,1,1,610,3.0,420.0,2,"french fries, chips, ice cream","boredom, stressed, sad",2.0,4.0,2,1.0,egan dining,2,1.0,poor,1,3,3,3.0,2,1.0,4.0,Vice President of a company,French,1,3.0,"hamburgers, chicken nuggets",1,5,1,3,1,a lot of greens,healthy and protien,7,6.0,1,5,3.0,1.0,"pasta, lasagna, chicken",4.0,stylist,4,1.0,5,4,1.0,2.0,1.0,1.0,3,940.0,345,softball,4,1,1315,150
35,3,1,1,610,2.0,420.0,2,"mac n cheese, peanut butter and banana sandwic...",Boredom usually,2.0,1.0,2,1.0,"A lot of rice and veggies, eggs for breakfast,...",3,1.0,My diet is more limited just because of what I...,1,3,2,3.0,2,1.0,4.0,Owns his own promotional company,American or Italian,5,1.0,"chicken, pasta, stir fry",1,5,3,3,2,"Some kind of protein, a vegetable, and a grain",Pretty much what I eat now,6,4.0,1,5,3.0,2.0,"Some kind of pasta, a chicken dish, some kind ...",4.0,Works in retail,2,2.0,1,3,2.0,2.0,1.0,1.0,2,940.0,690,Lacrosse,5,2,760,150
37,3.4,1,1,720,4.0,420.0,2,"chocolate, chips, candy",Stress,1.0,2.0,1,6.0,I do not get to eat as well as I did. I wish ...,2,2.0,I do not eat as many home cooked meals.,1,3,2,2.0,4,3.0,2.0,Construction,Italian,1,1.0,Pasta,1,3,4,5,4,"A protein, starch, veg, and a healthier dessert.",I would like to get all of the food groups in ...,2,6.0,3,5,2.0,2.0,"Pasta, Pizza, Chicken",3.0,Head of Human Resouces,4,1.0,1,4,3.0,4.0,1.0,1.0,5,940.0,500,Dancing,4,2,1315,170
38,3.89,1,1,610,3.0,980.0,2,"chocolate, popcorn, ice cream","boredom, stress",2.0,3.0,2,1.0,I eat three meals per day usually. I eat a lot...,1,1.0,I have eaten bigger meals.,1,2,2,3.0,4,2.0,4.0,Biohemical Waste Elimination,italian,1,1.0,chicken parmesan,1,4,4,3,6,a lean protein plus the addition of 2-3 fruits...,My ideal diet would be eating multiple fruits ...,2,5.0,3,5,8.0,2.0,"Chicken Parmesan, Orange Chicken, Tacos",4.0,Accountant,4,1.0,1,3,3.0,4.0,1.0,1.0,2,1165.0,690,Lacrosse,3,2,1315,150
40,3.4,2,1,430,3.0,315.0,1,"Pizza, Ice cream, fries, cereal, cookies",Usually if I'm sad or depressed.,3.0,3.0,3,1.0,I will eat a full bleakest every morning consi...,3,2.0,I eat pretty much the same as I use too. I do ...,1,9,2,3.0,4,1.0,4.0,Small business owner,Italian,1,1.0,"pizza, ice cream. pop tarts",1,3,1,5,10,A meal with all of the food groups.,Idealy I would have basically the same breakfa...,2,6.0,3,5,8.0,1.0,"Pizza, Japanize Hibachi, Moes",4.0,Middle school teacher,3,1.0,1,3,3.0,2.0,1.0,1.0,3,940.0,500,wrestling,4,2,760,140
44,3.2,1,1,610,4.0,420.0,2,"Potato chips, ice cream, chocolate, cookies","Stress, boredom, craving",1.0,1.0,1,1.0,"I am on a very balanced diet, eating 4-5 small...",1,1.0,"I haven't changed much. If anything, I have be...",2,4,2,2.0,5,1.0,4.0,Electrical Engineer,Thai food,4,1.0,"Mac and Cheese, Hot Dogs, Grilled Cheese",1,5,4,5,8,Mostly green!,My ideal diet would be to be a vegetarian; how...,7,5.0,5,5,10.0,1.0,"Steak, asparagus and potatoes, homemade chicke...",2.0,Secretary,4,2.0,1,6,5.0,3.0,1.0,1.0,5,725.0,500,Volleyball,5,1,760,170
46,3.8,2,1,430,2.0,420.0,1,"popcorn, chips, candy, & fries","sadness, boredom, & anger",3.0,3.0,3,1.0,At school I eat a lot of pizza or burgers with...,2,2.0,Eating more pizza and burgers or fast food.,1,2,2,2.0,4,2.0,3.0,subcontractor,Italian,1,1.0,"chicken soup, perogies, & roast beef",1,4,1,4,4,A meal that you have cooked yourself without a...,More of a home cooked meal that is not very gr...,5,4.0,3,5,4.0,1.0,"Spaghetti, steak, burgers",4.0,telemarketer,3,1.0,2,3,3.0,3.0,1.0,1.0,3,725.0,345,soccer,4,2,900,168
51,3.3,2,1,610,4.0,980.0,1,Burger,Lazy,5.0,3.0,5,1.0,Great,4,1.0,Mediocre,1,3,3,3.0,5,1.0,2.0,President of Automotive company,All,0,1.0,Steak,1,5,2,5,8,Chicken,Organic,5,6.0,5,5,8.0,1.0,"Steak, Chicken, Pasta",2.0,Stay home,5,1.0,1,3,5.0,2.0,1.0,1.0,5,1165.0,500,Hockey,4,1,1315,185
54,3.5,2,1,610,3.0,420.0,2,"peanut butter sandwich, pretzals, garlic bread","stress, anger and boredom",1.0,1.0,1,2.0,Very healthy and clean. A lot of protein and v...,1,1.0,I eat a lot more healthier,2,5,3,3.0,5,1.0,4.0,Sergeant correctional officer,Italian,1,1.0,Chicken Alfredo,2,5,2,5,10,High protein and vegetables,Clean diet. High protein intake.,7,6.0,4,5,10.0,1.0,"Chicken, Steak, Pasta",5.0,Teacher,4,1.0,1,6,2.0,2.0,1.0,1.0,4,940.0,690,hockey,5,1,900,165
56,3.8,2,1,720,4.0,315.0,2,"Pizza, Ice Cream, Chicken Wings",I usually only eat comfort foods when I am bor...,2.0,3.0,2,1.0,I usually eat very healthy. I incorporate fres...,1,1.0,I have begun to eat more fruits and vegetables...,2,5,4,3.0,5,1.0,4.0,Salesman,Thai,4,1.0,Meatloaf,1,5,4,4,1,Low protein and carbs and high in vegetables a...,My ideal diet is to cut back on my meat intake...,2,6.0,5,5,1.0,1.0,"Chicken, Beef, Steak",4.0,Nurse,4,2.0,1,4,4.0,2.0,1.0,1.0,5,1165.0,500,Hockey,5,1,1315,175
57,2.8,1,1,610,4.0,980.0,2,Pizza chocolate chips bagels ice Capps,Just cause,9.0,2.0,9,1.0,I eat very heathy on a daily basis,1,1.0,Really paid more attention to what I eat cause...,2,5,3,2.0,2,1.0,2.0,Owns his business,Wraps,5,3.0,Pizza pasta and quesadillas,2,4,2,5,9,Chicken and broccoli,"Fruits and vegetables, wheat bread, peanut but...",2,5.0,2,5,10.0,1.0,"chicken, pizza, stuffed shells",4.0,Sales,5,1.0,1,3,1.0,2.0,2.0,1.0,2,725.0,345,softball,4,1,1315,140
58,3.5,1,1,610,3.0,420.0,2,"Chocolate, ice cream, pasta","Stress, boredom, sadness",1.0,1.0,1,2.0,For breakfast I have oatmeal. For lunch I have...,3,2.0,More easy meals like pasta.,1,11,2,2.0,5,2.0,4.0,Physical Therapist,Mexican,2,1.0,Steak,2,5,3,5,4,"Fruit, vegetables, and protien",Ideally my diet would be similar to what I eat...,6,5.0,5,5,1.0,1.0,"steak, noodles, edemame",5.0,Elementary School Principal,2,2.0,1,4,4.0,3.0,1.0,1.0,5,1165.0,690,Skiing,5,1,1315,155
60,3.6,1,1,610,4.0,420.0,2,"peanut butter, dessets, pretzels.","Sadness, boredom, lonely.",3.0,2.0,3,1.0,"My diet consists of fruits, vegetables, grains...",1,2.0,At first I ate less but now that I'm in season...,3,4,5,3.0,5,1.0,4.0,Construction management,Mexican,2,1.0,lasagna,1,5,1,4,3,Half the plate fruit and vegetables. Other hal...,The way I eat now I think is pretty good.,6,6.0,1,5,5.0,1.0,"Lasagna, steak, chili",4.0,X-ray tech,4,1.0,1,3,1.0,2.0,1.0,1.0,1,1165.0,690,Water polo and running,5,1,1315,135
62,3.9,2,1,610,4.0,980.0,2,"ice cream, cookies, ice cream","boredom, sadness",2.0,3.0,2,1.0,I try to eat as healthy as possible. 3 meals a...,1,1.0,As an athlete it is important to fuel my body ...,2,5,5,2.0,2,1.0,2.0,police force,Italian,1,1.0,"Pizza, Pasta, Chicken",1,4,4,3,2,"high protein, low fat, low carbs and sugar","High protein, low fat",7,6.0,2,5,1.0,1.0,"pasta, chicken, vegetables",2.0,Legal assistant,4,1.0,2,3,2.0,2.0,1.0,1.0,2,1165.0,850,Ice Hockey,4,1,1315,210
64,3.5,1,1,610,3.0,420.0,1,"cookies, nutella, ice cream, coffee, fruit","Bordem, happiness, sadness",2.0,1.0,2,1.0,I eat fruit and vetagables with every meal. I ...,1,1.0,"I ate more junk food, but also more fruit.",1,3,3,2.0,4,1.0,2.0,Owner of New York Lunch,Chinese cuisine (General Tso's),4,3.0,"chicken stir fry, spaghetti, chicken parmesan",1,5,2,4,3,Meal prep'd foods with food from each section ...,I want to eliminate all the junk food I ate. B...,5,2.0,3,5,1.0,2.0,1. pasta 2. spaghetti 3. chicken and rice,2.0,CNA,4,1.0,1,2,3.0,4.0,2.0,1.0,3,940.0,500,Volleyball,5,1,760,140
67,3.6,1,1,610,2.0,420.0,1,"Ice cream, cake, mozzarella sticks, pierogies",Boredom,2.0,4.0,2,1.0,I typically try to eat healthy but being away ...,2,2.0,I eat a lot less than I did at home but find m...,1,3,3,2.0,5,2.0,2.0,Truck Driver,Italian,1,1.0,"Mac&Cheese, Chicken Nuggets",1,5,2,2,2,"It has protein, vegetables and some carbs",I would like to get more protein in me. I woul...,7,5.0,2,4,2.0,2.0,"Lasagna, Pizza, Pasta",3.0,Project Manager,2,1.0,2,4,1.0,2.0,1.0,1.0,2,940.0,690,"Recreational Basketball, Equestrian Team",5,2,1315,144 lbs
68,3.2,1,1,430,3.0,315.0,1,"Chips, Mac and cheese, pizza, French fries","Stress, sadness, bored",1.0,3.0,1,1.0,My current diet is balanced and includes food ...,1,2.0,I don't eat as healthy because there aren't as...,1,3,1,3.0,4,1.0,5.0,Dentist,Italian,1,1.0,"Pasta, pizza, meatballs",1,5,1,3,8,"Balanced between protein, veggies, and carbs",My ideal diet is a diet that makes me feel goo...,3,6.0,2,5,8.0,2.0,"pasta, chicken parm, tacos",5.0,school teacher,3,1.0,1,4,2.0,3.0,1.0,1.0,4,725.0,500,soccer,5,2,760,145
70,3.73,1,1,610,3.0,980.0,2,"Broccoli, spaghetti squash, quinoa, and grille...","Bad day, bored, sadness",2.0,3.0,2,1.0,Healthy and light,1,1.0,I don't eat as often,1,8,1,2.0,5,2.0,4.0,Retired - Bus Driver,Italian,1,1.0,Pizza and Spaghetti,2,5,3,5,3,"A vegetable, a protein, and a fruit",Healthy and light,1,3.0,5,5,2.0,2.0,"Pizza, Italian, anything chicken related",2.0,Stay-At-Home Mom,2,1.0,1,3,5.0,3.0,1.0,1.0,5,1165.0,500,Rec Volleyball,5,1,1315,140
73,3.79 bitch,2,1,720,4.0,420.0,2,"Chips, ice cream","Boredom, stress",2.0,1.0,2,1.0,I have a diet of meats and other high protein ...,2,2.0,I stopped drinking soda and only drink water now,2,12,4,3.0,3,1.0,4.0,Risk Manager,Mexican,2,1.0,Pizza,1,3,2,3,1,"Protein source, vegetables, fruits, whole grains",A balanced diet with each food group. Getting ...,3,6.0,1,5,2.0,2.0,"chipotle, chick fil a, chicken and rice",2.0,Customer Service,5,3.0,1,3,1.0,3.0,1.0,1.0,2,1165.0,850,baseball,4,1,1315,200

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [133]:
# Fix that in-place.
# 1. Force the 'weight' column to be numeric (invalid text becomes NaN)
df_food['weight'] = pd.to_numeric(df_food['weight'], errors='coerce')

# 2. Drop the rows containing those newly created NaNs in-place
df_food.dropna(subset=['weight'], inplace=True)

# 3. Print the data to verify it works
df_food

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,cook,comfort_food_reasons_coded.1,cuisine,diet_current,diet_current_coded,drink,eating_changes,eating_changes_coded,eating_changes_coded1,eating_out,employment,ethnic_food,exercise,father_education,father_profession,fav_cuisine,fav_cuisine_coded,fav_food,food_childhood,fries,fruit_day,grade_level,greek_food,healthy_feeling,healthy_meal,ideal_diet,ideal_diet_coded,income,indian_food,italian_food,life_rewarding,marital_status,meals_dinner_friend,mother_education,mother_profession,nutritional_check,on_off_campus,parents_cook,pay_meal_out,persian_food,self_perception_weight,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,2.0,9,NaN,eat good and exercise,1,1.0,eat faster,1,1,3,3.0,1,1.0,5.0,profesor,Arabic cuisine,3,1.0,rice and chicken,2,5,2,5,2,looks not oily,being healthy,8,5.0,5,5,1.0,1.0,"rice, chicken, soup",1.0,unemployed,5,1.0,1,2,5.0,3.0,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187.0
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,3.0,1,1.0,I eat about three times a day with some snacks...,2,2.0,I eat out more than usual.,1,2,2,2.0,4,1.0,2.0,Self employed,Italian,1,1.0,"chicken and biscuits, beef soup, baked beans",1,4,4,4,5,"Grains, Veggies, (more of grains and veggies),...",Try to eat 5-6 small meals a day. While trying...,3,4.0,4,4,1.0,2.0,"Pasta, steak, chicken",4.0,Nurse RN,4,1.0,1,4,4.0,3.0,1.0,1.0,2,725.0,690,Basketball,4,2,900,155.0
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,1.0,1,2.0,I try to eat healthy but often struggle becaus...,2,2.0,I have eaten generally the same foods but I do...,3,4,2,2.0,4,1.0,4.0,IT,Italian,1,3.0,"Pasta, chicken tender, pizza",1,4,4,4,6,"A lean protein such as grilled chicken, green ...",Ideally I would like to be able to eat healthi...,2,6.0,2,5,1.0,1.0,"Chicken Parmesan, Pulled Pork, Spaghetti and m...",5.0,Substance Abuse Conselor,3,1.0,1,4,2.0,4.0,1.0,1.0,4,940.0,500,Softball,4,2,760,190.0
5,2.25,1,1,610,3.0,980.0,2,"Candy, brownies and soda.","None, i don't eat comfort food. I just eat whe...",4.0,3.0,4,NaN,My current diet is terrible. I barely have tim...,2,2.0,Eating rice everyday. Eating less homemade food.,1,3,1,3.0,4,2.0,1.0,Taxi Driver,African,6,3.0,"Fries, plaintain & fried fish",1,2,2,2,4,"Requires veggies, fruits and a cooked meal.",My ideal diet is to eat 3 times a day includin...,2,1.0,5,5,4.0,2.0,Anything they'd want. I'd ask them before hand...,1.0,Hair Braider,1,1.0,2,5,5.0,5.0,1.0,2.0,4,940.0,345,None.,1,2,1315,190.0
6,3.8,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,2.0,1,1.0,I eat a lot of chicken and broccoli for dinner...,3,1.0,I started eating a lot less and healthier beca...,2,5,2,3.0,5,1.0,4.0,Assembler,Thai,4,1.0,"grilled chicken, hamburgers",1,4,4,5,4,"Protein, vegetables, fruit, and some carbs",I would ideally like to eat more fresh fruits ...,2,4.0,5,5,8.0,1.0,"Grilled chicken, steak, pizza",4.0,Journalist,4,2.0,2,2,5.0,4.0,1.0,1.0,5,940.0,690,soccer,4,1,1315,180.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.5,1,1,610,4.0,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,NaN,3.0,2,1.0,"My diet consists mainly of coffee, water, frui...",2,2.0,I have noticed there is less time for a prepar...,1,3,2,1.0,4,2.0,4.0,Accountant,Italian,1,1.0,Stromboli Mac and Cheese and Pizza,1,5,4,5,5,mainly protein and vegetables with a complex c...,My ideal diet would consist of a majority of w...,6,4.0,3,5,7.0,1.0,"pasta, fish, steak",3.0,Radiological Technician,5,3.0,1,4,3.0,4.0,1.0,1.0,5,940.0,500,Softball,5,1,1315,156.0
121,3,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,3.0,3,NaN,A college student with an imbalanced diet tryi...,2,1.0,Eating Pizza as an excuse when there is nothin...,1,3,4,3.0,3,2.0,5.0,Doctor,Mexican Food,2,1.0,"Isombe , Plantains and Ugali",1,4,4,1,5,"A healthy meal is a variety of food , organic ...",Eating home cooked meals everyday and being ab...,5,2.0,5,5,7.0,1.0,Fried Rice \rBaked potatoes \rCurry Chicken,2.0,Public Health Advisor,3,1.0,3,4,1.0,4.0,1.0,NaN,4,940.0,500,basketball,5,2,1315,180.0
122,3.882,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",sadness,NaN,3.0,3,NaN,"Rice, oatmeal, and tea",2,1.0,less rice,1,3,3,3.0,5,2.0,5.0,CEO of company,Korean,4,1.0,Rice and potato,1,4,3,5,6,lots of vegetables,lots of veggies,2,2.0,5,3,10.0,1.0,"meat, rice, kimchi",1.0,Real Estate manageer,3,1.0,2,4,5.0,4.0,1.0,2.0,5,580.0,690,none,4,2,1315,120.0
123,3,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,3.0,7,1.0,I try to eat as healthy as possible everyday. ...,1,2.0,I don't eat as much on a daily basis since com...,1,8,5,2.0,2,1.0,3.0,Store manager at Giant Eagle,Italian,1,3.0,pizza and spaghetti,1,5,1,1,1,"A protein, a fruit, a starch, and a salad or s...",My ideal diet is the diet i am currently on. ...,6,4.0,1,5,1.0,1.0,"Pizza, Spaghetti, Baked Ziti",2.0,Receptionist for a medical supply company,4,1.0,2,3,1.0,2.0,2.0,2.0,1,940.0,500,NaN,3,1,1315,135.0
124,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,NaN,5,3.0,high in protein and low in carbohydrates.,1,1.0,I have learned to eat more vegetables.,2,5,1,2.0,3,2.0,4.0,Journalist,HISPANIC CUISINE.,2,1.0,"rice, beans, and chicken / pizza/ tenders",1,3,3,2,3,"a cup of rice, vegetables, and meat.","Being able to balance between sweets, vegetabl...",3,5.0,2,3,5.0,2.0,"Vegetables, Meat, and rice.",3.0,House-wife,5,1.0,3,3,2.0,3.0,1.0,2.0,2,725.0,345,NaN,4,2,575,135.0

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [137]:
# Savey save!
cleaned_food_data_set_path = 'data/food_coded_cleaned.csv'
df_food.to_csv(cleaned_food_data_set_path, index=False)

In [138]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.
df_food_cleaned = pd.read_csv(cleaned_food_data_set_path)
df_food_cleaned.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,cook,comfort_food_reasons_coded.1,cuisine,diet_current,diet_current_coded,drink,eating_changes,eating_changes_coded,eating_changes_coded1,eating_out,employment,ethnic_food,exercise,father_education,father_profession,fav_cuisine,fav_cuisine_coded,fav_food,food_childhood,fries,fruit_day,grade_level,greek_food,healthy_feeling,healthy_meal,ideal_diet,ideal_diet_coded,income,indian_food,italian_food,life_rewarding,marital_status,meals_dinner_friend,mother_education,mother_profession,nutritional_check,on_off_campus,parents_cook,pay_meal_out,persian_food,self_perception_weight,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,2.0,9,NaN,eat good and exercise,1,1.0,eat faster,1,1,3,3.0,1,1.0,5.0,profesor,Arabic cuisine,3,1.0,rice and chicken,2,5,2,5,2,looks not oily,being healthy,8,5.0,5,5,1.0,1.0,"rice, chicken, soup",1.0,unemployed,5,1.0,1,2,5.0,3.0,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187.0
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,3.0,1,1.0,I eat about three times a day with some snacks...,2,2.0,I eat out more than usual.,1,2,2,2.0,4,1.0,2.0,Self employed,Italian,1,1.0,"chicken and biscuits, beef soup, baked beans",1,4,4,4,5,"Grains, Veggies, (more of grains and veggies),...",Try to eat 5-6 small meals a day. While trying...,3,4.0,4,4,1.0,2.0,"Pasta, steak, chicken",4.0,Nurse RN,4,1.0,1,4,4.0,3.0,1.0,1.0,2,725.0,690,Basketball,4,2,900,155.0
2,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,1.0,1,2.0,I try to eat healthy but often struggle becaus...,2,2.0,I have eaten generally the same foods but I do...,3,4,2,2.0,4,1.0,4.0,IT,Italian,1,3.0,"Pasta, chicken tender, pizza",1,4,4,4,6,"A lean protein such as grilled chicken, green ...",Ideally I would like to be able to eat healthi...,2,6.0,2,5,1.0,1.0,"Chicken Parmesan, Pulled Pork, Spaghetti and m...",5.0,Substance Abuse Conselor,3,1.0,1,4,2.0,4.0,1.0,1.0,4,940.0,500,Softball,4,2,760,190.0
3,2.25,1,1,610,3.0,980.0,2,"Candy, brownies and soda.","None, i don't eat comfort food. I just eat whe...",4.0,3.0,4,NaN,My current diet is terrible. I barely have tim...,2,2.0,Eating rice everyday. Eating less homemade food.,1,3,1,3.0,4,2.0,1.0,Taxi Driver,African,6,3.0,"Fries, plaintain & fried fish",1,2,2,2,4,"Requires veggies, fruits and a cooked meal.",My ideal diet is to eat 3 times a day includin...,2,1.0,5,5,4.0,2.0,Anything they'd want. I'd ask them before hand...,1.0,Hair Braider,1,1.0,2,5,5.0,5.0,1.0,2.0,4,940.0,345,None.,1,2,1315,190.0
4,3.8,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,2.0,1,1.0,I eat a lot of chicken and broccoli for dinner...,3,1.0,I started eating a lot less and healthier beca...,2,5,2,3.0,5,1.0,4.0,Assembler,Thai,4,1.0,"grilled chicken, hamburgers",1,4,4,5,4,"Protein, vegetables, fruit, and some carbs",I would ideally like to eat more fresh fruits ...,2,4.0,5,5,8.0,1.0,"Grilled chicken, steak, pizza",4.0,Journalist,4,2.0,2,2,5.0,4.0,1.0,1.0,5,940.0,690,soccer,4,1,1315,180.0

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [157]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.
df_salary = pd.read_csv('/home/muharem/VSCode_Projects/Cuny_Tech_Prep/ds-fall-2026/Week-02-Pandas-and-How-to-Make-a-Sick-Project/data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv',sep='\t')
df_salary

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28057,7/12/2024 22:52:01,35-44,Health care,Veterinarian,NaN,135000,NaN,USD,NaN,NaN,United States,Missouri,Wentzville,11 - 20 years,11 - 20 years,"Professional degree (MD, JD, etc.)",Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28059,7/24/2024 12:22:58,18-24,"Accounting, Banking & Finance",Risk Management Associate,NaN,1200,0.0,USD,NaN,NaN,Myanmar,Colorado,Yangon,2 - 4 years,2 - 4 years,Some college,Man,Asian or Asian American
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American
28061,8/20/2024 1:06:13,25-34,Health care,Clinical physiologist,NaN,1200000,NaN,Other,NGN,NaN,Nigeria,NaN,Lagos,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [158]:
# Count by hand. I’m dead serious.

print(f"Nice try ... but no: {len(df_salary)}")

Nice try ... but no: 28062

What are the columns and their types?

In [159]:
# Show the column names and their types.
df_salary.head(0).dtypes

Timestamp                                                                                                                                                                                                                                   str
How old are you?                                                                                                                                                                                                                            str
What industry do you work in?                                                                                                                                                                                                               str
Job title                                                                                                                                                                                                                                   str
If your job title needs additional context, please clarify here:                                                                                                                                                                            str
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        str
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                                str
If "Other," please indicate the currency here:                                                                                                                                                                                              str
If your income needs additional context, please provide it here:                                                                                                                                                                            str
What country do you work in?                                                                                                                                                                                                                str
If you're in the U.S., what state do you work in?                                                                                                                                                                                           str
What city do you work in?                                                                                                                                                                                                                   str
How many years of professional work experience do you have overall?                                                                                                                                                                         str
How many years of professional work experience do you have in your field?                                                                                                                                                                   str
What is your highest level of education completed?                                                                                                                                                                                          str
What is your gender?                                                                                                                                                                                                                        str
What is your race? (Choose all that apply.)                                                                                                                                                                                                 str
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [173]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race
clean_names = [
    'timestamp', 'age', 'industry', 'title', 'title_context', 'salary', 
    'additional_compensation', 'currency', 'other_currency', 'salary_context', 
    'country', 'state', 'city', 'total_yoe', 'field_yoe', 
    'highest_education_completed', 'gender', 'race'
]
df_salary.rename(columns=dict(zip(df_salary.columns, clean_names)), inplace=True)
df_salary.head(0).dtypes

timestamp                      str
age                            str
industry                       str
title                          str
title_context                  str
salary                         str
additional_compensation    float64
currency                       str
other_currency                 str
salary_context                 str
country                        str
state                          str
city                           str
total_yoe                      str
gender                         str
race                           str
gender                         str
race                           str
dtype: object

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [174]:
# List the unique industries and a count of their instances.

df_salary['industry'].value_counts()

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [176]:
# Filtery filter.
df_salary_tech = df_salary[df_salary['industry'].str.contains('tech', case=False, na=False)]

Do a sanity check by counting.

In [177]:
# Sanity check count.
len(df_salary_tech)

4867

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [179]:
# Filtery filter (in place) for just the jobs that pay in USD!
df_salary_tech_usd = df_salary_tech[df_salary_tech['currency'].str.contains('USD', case=False, na=False)]
df_salary_tech_usd

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,gender,race,gender,race
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,"200,850",40000.0,USD,NaN,NaN,USA,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28044,6/3/2024 16:15:43,18-24,Computing or Tech,Research Data Analyst Associate,NaN,60000,0.0,USD,NaN,NaN,United States,Illinois,Evanston,2 - 4 years,1 year or less,College degree,Woman,White
28051,7/1/2024 20:05:58,25-34,Computing or Tech,Junior data analyst,NaN,35000,15000.0,USD,NaN,NaN,Usa,Alabama,Alabama,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American
28052,7/3/2024 14:02:01,25-34,Computing or Tech,Senior Global Public Relations Manager,NaN,144000,15000.0,USD,NaN,NaN,Usa,Massachusetts,Boise-but remote. Company located in Boston,8 - 10 years,8 - 10 years,Master's degree,Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [181]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
country_counts = df_salary_tech_usd['country'].value_counts()
country_counts

country
United States                1626
USA                          1290
US                            426
U.S.                          112
United States of America       94
United States                  71
Usa                            62
USA                            61
usa                            29
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
U.S                             2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [182]:
# Replace them all in-place with 'US'.
df_top_5_countries = country_counts.head(5).index.tolist()
df_salary_tech_usd['country'] = df_salary_tech_usd['country'].replace(df_top_5_countries, 'US')
df_salary_tech_usd['country'].value_counts().head(5)

country
US                3548
United States       71
Usa                 62
USA                 61
usa                 29
Name: count, dtype: int64

Have a look at the count of each unique country again now.

In [183]:
# Count again.

len(df_salary_tech_usd)

3929

Did you notice anything interesting?

In [ ]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [ ]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [184]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
df_salary_tech_usd.groupby('state')['salary'].agg(['min', 'mean', 'max']).reset_index()

TypeError: dtype 'str' does not support operation 'mean'

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [185]:
# Fix it in-place.
df_salary_tech_usd['salary'] = pd.to_numeric(df_salary_tech_usd['salary'], errors='coerce')

Let’s try that again.

In [186]:
# Try it again. Yeah!
df_salary_tech_usd.groupby('state')['salary'].agg(['min', 'mean', 'max']).reset_index()

                             state       min           mean        max
0                          Alabama   35000.0  117400.000000   350000.0
1    Alabama, District of Columbia       NaN            NaN        NaN
2                 Alabama, Montana       NaN            NaN        NaN
3                           Alaska       NaN            NaN        NaN
4                 Alaska, Maryland       NaN            NaN        NaN
5                          Arizona   35000.0   97833.333333   145000.0
6                    Arizona, Utah       NaN            NaN        NaN
7                         Arkansas       4.0   58001.000000    95000.0
8                       California       0.0  150893.113990   520000.0
9             California, Colorado  176000.0  176000.000000   176000.0
10            California, Maryland   81500.0   81500.000000    81500.0
11              California, Oregon  200000.0  200000.000000   200000.0
12                        Colorado   49400.0  108994.871795   165000.0
13                     Connecticut   68000.0  150508.333333   270000.0
14                        Delaware  169000.0  169000.000000   169000.0
15            District of Columbia   59000.0  142923.076923   200000.0
16  District of Columbia, Virginia  109200.0  109200.000000   109200.0
17                         Florida   28800.0  210711.000000  2600000.0
18                         Georgia   29120.0  115297.647059   242000.0
19          Georgia, Massachusetts       NaN            NaN        NaN
20             Georgia, Washington       NaN            NaN        NaN
21                           Idaho   74860.0  105465.000000   170000.0
22                        Illinois   36000.0  117555.571429   228800.0
23                         Indiana   15000.0   82875.000000   140000.0
24                            Iowa   63000.0  101200.000000   142000.0
25                          Kansas   41500.0  109666.666667   167000.0
26                        Kentucky   62000.0  117000.000000   175000.0
27                       Louisiana   75000.0   80500.000000    84000.0
28           Louisiana, Washington  117000.0  117000.000000   117000.0
29                           Maine   50000.0  103833.333333   173000.0
30                        Maryland   62000.0  120858.642857   176000.0
31                   Massachusetts   41000.0  122081.702128   400000.0
32    Massachusetts, New Hampshire       NaN            NaN        NaN
33     Massachusetts, Pennsylvania       NaN            NaN        NaN
34     Massachusetts, Rhode Island       NaN            NaN        NaN
35                        Michigan   41600.0   93310.526316   235000.0
36     Michigan, Texas, Washington  340000.0  340000.000000   340000.0
37                       Minnesota   42000.0   97783.555556   210000.0
38                     Mississippi       NaN            NaN        NaN
39                        Missouri      80.0   80339.923077   200000.0
40                         Montana   65000.0  112666.666667   145000.0
41                        Nebraska   43000.0   76736.000000   140000.0
42                          Nevada  107100.0  124550.000000   142000.0
43                   New Hampshire      55.0   87175.833333   130000.0
44                      New Jersey   67500.0  124090.909091   192000.0
45            New Jersey, New York  135000.0  137500.000000   140000.0
46                      New Mexico   82000.0   95733.333333   115200.0
47                        New York   14000.0  146486.759259   590000.0
48                 New York, Texas       NaN            NaN        NaN
49                  North Carolina   29000.0   97841.666667   165000.0
50                    North Dakota       NaN            NaN        NaN
51                            Ohio   42000.0  137066.666667   954000.0
52                        Oklahoma   36958.0   84802.571429   180000.0
53                          Oregon   16200.0  122640.000000   230000.0
54                    Pennsylvania   52000.0  116826.388889   237000.0
55                    Rhode Island   76000.0   99475.000000   122950.0
56                  South Carolina   40000.0   40000.000000    40000.0
57                    South Dakota       NaN            NaN        NaN
58                       Tennessee   61500.0   91750.000000   144000.0
59                           Texas   10700.0  103625.032258   190000.0
60                            Utah   33280.0  105023.333333   176000.0
61                   Utah, Vermont       NaN            NaN        NaN
62                         Vermont   91250.0  105625.000000   120000.0
63                        Virginia   58750.0  115086.696970   378000.0
64                      Washington      72.0  136923.916667   300000.0
65                   West Virginia  120000.0  120000.000000   120000.0
66                       Wisconsin       1.0  145806.888889   920000.0

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [187]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.
df_salary_tech_usd_filtered = df_salary_tech_usd[df_salary_tech_usd['timestamp'].str.contains('2021|2022|2023', na=False)]
df_salary_tech_usd_filtered.groupby('state')['salary'].agg(['min', 'mean', 'max']).reset_index()

                             state       min           mean       max
0                          Alabama   52000.0  138000.000000  350000.0
1    Alabama, District of Columbia       NaN            NaN       NaN
2                 Alabama, Montana       NaN            NaN       NaN
3                           Alaska       NaN            NaN       NaN
4                 Alaska, Maryland       NaN            NaN       NaN
5                          Arizona   35000.0   97833.333333  145000.0
6                    Arizona, Utah       NaN            NaN       NaN
7                         Arkansas   60000.0   77333.333333   95000.0
8                       California       0.0  151314.432292  520000.0
9             California, Colorado  176000.0  176000.000000  176000.0
10            California, Maryland   81500.0   81500.000000   81500.0
11              California, Oregon  200000.0  200000.000000  200000.0
12                        Colorado   49400.0  108994.871795  165000.0
13                     Connecticut   68000.0  150508.333333  270000.0
14                        Delaware  169000.0  169000.000000  169000.0
15            District of Columbia   59000.0  142923.076923  200000.0
16  District of Columbia, Virginia  109200.0  109200.000000  109200.0
17                         Florida   28800.0  102106.954545  170000.0
18                         Georgia   29120.0  115488.484848  242000.0
19          Georgia, Massachusetts       NaN            NaN       NaN
20             Georgia, Washington       NaN            NaN       NaN
21                           Idaho   74860.0  105465.000000  170000.0
22                        Illinois   36000.0  119248.382353  228800.0
23                         Indiana   15000.0   82875.000000  140000.0
24                            Iowa   63000.0  101200.000000  142000.0
25                          Kansas   41500.0  109666.666667  167000.0
26                        Kentucky   62000.0  117000.000000  175000.0
27                       Louisiana   75000.0   80500.000000   84000.0
28           Louisiana, Washington  117000.0  117000.000000  117000.0
29                           Maine   50000.0  103833.333333  173000.0
30                        Maryland   62000.0  120858.642857  176000.0
31                   Massachusetts   41000.0  121846.021505  400000.0
32    Massachusetts, New Hampshire       NaN            NaN       NaN
33     Massachusetts, Pennsylvania       NaN            NaN       NaN
34     Massachusetts, Rhode Island       NaN            NaN       NaN
35                        Michigan   41600.0   93310.526316  235000.0
36     Michigan, Texas, Washington  340000.0  340000.000000  340000.0
37                       Minnesota   42000.0   98829.647059  210000.0
38                     Mississippi       NaN            NaN       NaN
39                        Missouri      80.0   80339.923077  200000.0
40                         Montana   65000.0  112666.666667  145000.0
41                        Nebraska   43000.0   76736.000000  140000.0
42                          Nevada  107100.0  124550.000000  142000.0
43                   New Hampshire      55.0   87175.833333  130000.0
44                      New Jersey   67500.0  124090.909091  192000.0
45            New Jersey, New York  135000.0  137500.000000  140000.0
46                      New Mexico   82000.0   95733.333333  115200.0
47                        New York   14000.0  146486.759259  590000.0
48                 New York, Texas       NaN            NaN       NaN
49                  North Carolina   29000.0   97250.000000  165000.0
50                    North Dakota       NaN            NaN       NaN
51                            Ohio   42000.0  137066.666667  954000.0
52                        Oklahoma   36958.0   84802.571429  180000.0
53                          Oregon   16200.0  122640.000000  230000.0
54                    Pennsylvania   52000.0  116826.388889  237000.0
55                    Rhode Island   76000.0   99475.000000  122950.0
56                  South Carolina       NaN            NaN       NaN
57                    South Dakota       NaN            NaN       NaN
58                       Tennessee   61500.0   91750.000000  144000.0
59                           Texas   10700.0  103625.032258  190000.0
60                            Utah   33280.0  105023.333333  176000.0
61                   Utah, Vermont       NaN            NaN       NaN
62                         Vermont   91250.0  105625.000000  120000.0
63                        Virginia   58750.0  115086.696970  378000.0
64                      Washington      72.0  137427.774648  300000.0
65                   West Virginia  120000.0  120000.000000  120000.0
66                       Wisconsin       1.0  145806.888889  920000.0

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)